### PR TITLE
Comment on PR

### PR DESCRIPTION
**Pull request by caleeli**
## Expected behavior: 
Add PR comment with test results.

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by caleeli** [comment]
## send a comment to GitHub PR
working fine!

**Comment by caleeli** [comment]
## lighthouse test
**Loop6 multi-column select lists rich texts text areas**

performance record is 15 and threshold was 12
accessibility record is 95 and threshold was 50
interactive record is 10984.06755 and threshold was 16000

**Comment by pmkerberos** [comment]
## lighthouse test
**Loop6 multi-column select lists rich texts text areas**

performance record is 16 and threshold was 12
accessibility record is 95 and threshold was 50
interactive record is 10736.044550000002 and threshold was 16000

**Comment by pmkerberos** [comment]
## lighthouse test
**Loop6 multi-column select lists rich texts text areas validations rules visibility rules and submit button**

performance record is 16 and threshold was 12
accessibility record is 95 and threshold was 50
interactive record is 10735.998649999994 and threshold was 16000

**Review by rodriquelca — APPROVED** [review]

**Pull request merged**
