### PR TITLE
Required Field Display Improvements

### PR DESCRIPTION
**Pull request by nolanpro**
## Issue & Reproduction Steps

This feature
- Adds a red required asterisk to required fields.
- Only shows the error message and red outline after the user clicks submit and the validation rules are not met.

## How to Test
- Create form with an element that has required validation
- Verify the red asterisk is always shown
- Verify the message and red outline is only shown after the user clicks submit
- Try with 'required if' and 'require unless' rules. The asterisk should only show if needed.
- Try in different screen setups such as nested screens, loops, pages, etc.

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-8092
- These PRs are for both FOUR-8093 and FOUR-8094
- Required PRs
  - https://github.com/ProcessMaker/processmaker/pull/4790
  - https://github.com/ProcessMaker/vue-form-elements/pull/397
  - https://github.com/ProcessMaker/package-signature/pull/31

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy
ci:processmaker:feature/FOUR-8093
ci:vue-form-elements:feature/FOUR-8093
ci:package-signature:feature/FOUR-8093
.....

### CODE REVIEW

**Review by eiresendez — CHANGES_REQUESTED** [review]
Hi @nolanpro I have some observations, please ignore what doesn't apply:

Important notes:
- Conversational form preview is broken: `Error in v-on handler: "TypeError: this.$refs.renderer is undefined"`.

General notes:
- At first, when toggling the checkbox, the error message is not displayed. But, if I click on submit and then toggle again, the error message is shown without having to click submit again. If this is correct, please ignore it.
  - This happens with all elements.
- When clicking on submit and the required field error message is displayed, the button becomes disabled but still allows clicks. I think that in addition to adding the "disabled" class, the disabled attribute should also be added.
- When using nested screens, the submit button is always disabled by default until we click on it and there are no required fields.
  - This doesn't happen in a screen without nested screens. The disabled class is applied and removed appropriately.
- captcha
  - NOTE: The captcha field does not have an asterisk nor a "required field" message. Prob. not a requirement?.

Tests:
- tested `required`, `required_if` and `required_unless` rules - passed.
- checkbox (passed)
- date picker (passed)
- file upload (passed)
- loop (passed)
- nested screen (passed)
- pages (passed)
- select list (passed)
- signature (passed)
- textarea (passed)
- file download, file preview, google places, image, multicolumn, page navigation, record list, rich text, saved search chart, submit button (not applicable)

**Comment by nolanpro** [comment]
@eiresendez
- Fixed the conversational form error
- Always displaying the error after the first time the user clicks submit is expected behavior, I think
- I think the issues with the submit button are separate issues outside the context of this feature. The issues existed this PR and should be a separate Jira issue
- Its not needed for Captcha

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-96c317084f.eng.processmaker.net

**Review by eiresendez — APPROVED** [review]
Great! Conversational Forms preview works! I agree with the other comments!

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-96c317084f.eng.processmaker.net

**Review by boliviacoca — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-96c317084f.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-96c317084f.eng.processmaker.net

**Pull request merged**
