### PR TITLE
FOUR-13457 order watchers list with drag and drop option

### PR DESCRIPTION
**Pull request by devmiguelangel**
## Issue & Reproduction Steps
As a designer I want to have the option to Order the list of Watchers that I am creating in the Screen Builder.

## Solution

https://github.com/ProcessMaker/screen-builder/assets/3604190/a8e6fea7-be2f-464c-ae9a-d8bfaf37afc6

## Related Tickets & Packages
[FOUR-13457](https://processmaker.atlassian.net/browse/FOUR-13457)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:next

[FOUR-13457]: https://processmaker.atlassian.net/browse/FOUR-13457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rodriquelca** [comment]
please review https://sonarqube.processmaker.net/component_measures?id=ProcessMaker_screen-builder_AYlHjxBBxYvY_isvKt7h&pullRequest=1625&metric=new_coverage&view=list

duplicated code

**Comment by devmiguelangel** [comment]
@rodriquelca the duplicated code was already fixed
https://sonarqube.processmaker.net/component_measures?id=ProcessMaker_screen-builder_AYlHjxBBxYvY_isvKt7h&pullRequest=1625&metric=new_duplicated_lines_density&view=list

**Comment by rodriquelca** [comment]
resizing the window I have the next view
Screenshot 2024-06-19 at 4 46 12 PM

**Comment by devmiguelangel** [comment]
@rodriquelca As we discussed, a scroll was added to the `Sortable` component

**Review by rodriquelca — APPROVED** [review]

**Pull request merged**
